Rails.application.routes.draw do
  get 'welcome/index'

  root 'welcome#index'
  get 'welcome/login'
  get 'welcome/cliente'
  get 'welcome/crear_caso'
  get 'welcome/caso_creado'
  get 'welcome/consultor'
  post 'welcome/login'
  post 'welcome/index'
  post 'welcome/cliente'
  post 'welcome/consultor'
  post 'welcome/admin'
  post 'welcome/crear_caso'
  post 'welcome/caso_creado'
  get 'welcome/cerrar_caso'
  post 'welcome/cerrar_caso'
  get 'welcome/admin'
  post 'welcome/crear_usuario'
  get 'welcome/crear_usuario'
  post 'welcome/usuario_creado'
  get 'welcome/usuario_creado'
  post 'welcome/login_error'
  get 'welcome/login_error'
  post 'welcome/vista_caso'
  get 'welcome/vista_caso'
  post 'welcome/crear_usuario_vista'
  get 'welcome/crear_usuario_vista'
  post 'welcome/admin_casos'
  get 'welcome/admin_casos'
  post 'welcome/asignar'
  get 'welcome/asignar'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
