# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b24ead0fe25b1a062b29ddb8d85175c3d4cae888047a39f0b88e2fac7da22e96ff20e2a2644a689f7fcd3a9c9493c1e8f7d34718f479edca6f71fc7989f61b9

test:
  secret_key_base: 41a3d813d0b08c2defe2d3337d59356d5688bd81d1642b728a195f940a8d0e6e97aee6c7368d2c13f05845c15b6e4fc5e2ec945da49469ec9e7a217cf141c5f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
